/*
 * -------------------------------------------------------
 * Section: Role Permissions
 * Create role permissions mapping table and helper functions
 * -------------------------------------------------------
 */

-- Create table for role permissions
create table if not exists public.role_permissions (
  id bigint generated by default as identity primary key,
  role varchar(50) references public.roles (name) not null,
  permission public.app_permissions not null,
  unique (role, permission)
);

-- Indexes
create index if not exists idx_role_permissions_role on public.role_permissions (role);
create index if not exists idx_role_permissions_permission on public.role_permissions (permission);


-- Revoke all on role_permissions table from authenticated and service_role
revoke all on public.role_permissions
from authenticated, service_role;

-- Grants
grant select, insert, update, delete on table public.role_permissions to service_role;
grant select on table public.role_permissions to authenticated;

-- Functions
create or replace function public.has_permission (
  user_id uuid,
  permission_name public.app_permissions
) returns boolean
set search_path = '' as $$
begin
  return exists(
    select 1
    from public.accounts
    join public.role_permissions
      on accounts.role = role_permissions.role
    where accounts.id = has_permission.user_id
      and role_permissions.permission = has_permission.permission_name
  );
end;
$$ language plpgsql;

grant execute on function public.has_permission (uuid, public.app_permissions) to authenticated, service_role;
